"""Quantum recurrent language model: a learnable quantum hidden Markov model.

v0.4 diagnosis: monitored-dynamics data is generated by RECURRENT quantum
memory, but our quantum layers were feed-forward per token — a model-class
mismatch. This module closes it. ``QRNNLM`` carries a statevector across
tokens and, per position:

  1. **collapse** onto the block of the observed token (exact Bayes
     conditioning of the quantum belief state, teacher-forced),
  2. **inject** learnable RY re-preparation angles keyed by the token,
  3. **evolve** under a trainable entangling unitary (Rot + CNOT-ring
     layers, the state-space twin of our circuit ansatz),
  4. **emit** next-token logits from the Born probabilities of the
     emission qubits.

The model class literally CONTAINS the v0.4 data generator (kicked-Ising
+ projective emission), so with n_qubits = generator qubits it can in
principle reach the ideal entropy floor with ~tens of parameters, where
classical models must approximate a belief-state filter of dimension
~4^m in the memory size m. Everything is a pure-state simulation in JAX:
smooth, jit/scan/grad-friendly (the renormalized collapse is
differentiable; the sampling lives only in the data).

The trainable unitary parameters are named ``circuit_weights`` so the
existing freezing (``trainable: false``) and gradient-norm telemetry
apply unchanged.
"""
from __future__ import annotations

import math

import jax
import jax.numpy as jnp
import numpy as np
from flax import linen as nn

from ..config import ModelConfig

_CNOT = jnp.asarray(
    np.array(
        [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]],
        dtype=np.complex64,
    )
)


def _apply_1q(psi: jnp.ndarray, gate: jnp.ndarray, qubit: int, n: int):
    """Apply a 2x2 gate to ``qubit`` of psi (B, 2**n). gate: (2,2) or (B,2,2)."""
    batch = psi.shape[0]
    t = psi.reshape((batch,) + (2,) * n)
    t = jnp.moveaxis(t, 1 + qubit, -1)
    if gate.ndim == 2:
        t = jnp.einsum("...i,ij->...j", t, gate.T)
    else:
        t = jnp.einsum("b...i,bij->b...j", t, jnp.swapaxes(gate, -1, -2))
    t = jnp.moveaxis(t, -1, 1 + qubit)
    return t.reshape(batch, -1)


def _apply_cnot(psi: jnp.ndarray, control: int, target: int, n: int):
    batch = psi.shape[0]
    t = psi.reshape((batch,) + (2,) * n)
    t = jnp.moveaxis(t, (1 + control, 1 + target), (-2, -1))
    shape = t.shape
    t = t.reshape(*shape[:-2], 4) @ _CNOT.T
    t = t.reshape(shape)
    t = jnp.moveaxis(t, (-2, -1), (1 + control, 1 + target))
    return t.reshape(batch, -1)


def _rot(phi, theta, omega):
    """qml.Rot-equivalent 2x2: RZ(omega) RY(theta) RZ(phi)."""
    c, s = jnp.cos(theta / 2), jnp.sin(theta / 2)
    return jnp.array(
        [
            [jnp.exp(-0.5j * (phi + omega)) * c, -jnp.exp(0.5j * (phi - omega)) * s],
            [jnp.exp(0.5j * (omega - phi)) * s, jnp.exp(0.5j * (phi + omega)) * c],
        ]
    )


def _ry(angle):
    c, s = jnp.cos(angle / 2), jnp.sin(angle / 2)
    return jnp.stack(
        [jnp.stack([c, -s], -1), jnp.stack([s, c], -1)], -2
    ).astype(jnp.complex64)


class QRNNLM(nn.Module):
    """Recurrent quantum LM. Requires vocab_size = 2**k with k < n_qubits."""

    vocab_size: int
    n_qubits: int = 6
    n_layers: int = 3
    init_scale: float = 2.0 * math.pi
    entangler: str = "cnot_ring"  # cnot_ring | none (Ising form: ZZ+Rot only)

    @nn.compact
    def __call__(self, tokens: jnp.ndarray) -> jnp.ndarray:
        n, v = self.n_qubits, self.vocab_size
        k = int(round(math.log2(v)))
        assert 2**k == v and k < n, (
            f"QRNNLM needs vocab_size=2**k with k < n_qubits (got V={v}, n={n})"
        )
        batch, _ = tokens.shape
        rest = 2 ** (n - k)

        circuit_weights = self.param(
            "circuit_weights",
            nn.initializers.uniform(scale=self.init_scale),
            (self.n_layers, n, 3),
        )
        zz_phase = self.param(
            "zz_phase",
            nn.initializers.uniform(scale=self.init_scale),
            (self.n_layers,),
        )
        inject_angles = self.param(
            "inject_angles", nn.initializers.normal(stddev=0.5), (v, n)
        )
        logit_scale = self.param("logit_scale", nn.initializers.ones, ())
        logit_bias = self.param("logit_bias", nn.initializers.zeros, (v,))

        # ring-ZZ eigenvalues (diagonal in the computational basis) — with
        # these, one layer is exactly the kicked-Ising Floquet form
        # U_x . U_zz, so the model class CONTAINS the v0.4 generator.
        basis = np.arange(2**n)
        bits = (basis[:, None] >> (n - 1 - np.arange(n))[None, :]) & 1
        zsign = 1 - 2 * bits
        zz_vec = jnp.asarray(
            (zsign * np.roll(zsign, -1, axis=1)).sum(axis=1).astype(np.float32)
        )

        # NOTE: with entangler="cnot_ring" every layer forcibly applies an
        # entangling Clifford the kicked-Ising generator does NOT contain —
        # single-qubit rotations cannot cancel it, so exact representability
        # fails. entangler="none" (Ising form: ZZ phase + Rot only) contains
        # U_F**k exactly at n_layers = k.
        def evolve(psi):
            for layer in range(self.n_layers):
                psi = psi * jnp.exp(-1j * zz_phase[layer] * zz_vec)[None, :]
                for q in range(n):
                    psi = _apply_1q(
                        psi, _rot(*circuit_weights[layer, q]), q, n
                    )
                if self.entangler == "cnot_ring" and n > 1:
                    for q in range(n):
                        psi = _apply_cnot(psi, q, (q + 1) % n, n)
            return psi

        def step(psi, x_t):
            # 1) collapse onto the observed token's emission block
            blocks = psi.reshape(batch, v, rest)
            onehot = jax.nn.one_hot(x_t, v, dtype=psi.real.dtype)
            picked = blocks * onehot[:, :, None]
            norm = jnp.sqrt(
                (jnp.abs(picked) ** 2).sum(axis=(1, 2), keepdims=True) + 1e-12
            )
            psi = (picked / norm).reshape(batch, -1)
            # 2) learnable re-preparation keyed by the token
            angles = inject_angles[x_t]  # (B, n)
            for q in range(n):
                psi = _apply_1q(psi, _ry(angles[:, q]), q, n)
            # 3) trainable unitary evolution
            psi = evolve(psi)
            # 4) emit: Born probabilities of the emission qubits
            p = (jnp.abs(psi.reshape(batch, v, rest)) ** 2).sum(axis=2)
            logits = logit_scale * jnp.log(p + 1e-9) + logit_bias
            return psi, logits

        # uniform superposition start (every emission block populated)
        dim = 2**n
        psi0 = jnp.full((batch, dim), 1.0 / math.sqrt(dim), dtype=jnp.complex64)

        xs = jnp.swapaxes(tokens, 0, 1)  # (T, B)
        _, ys = jax.lax.scan(step, psi0, xs)
        return jnp.swapaxes(ys, 0, 1)  # (B, T, V)


def qrnn_from_config(cfg: ModelConfig) -> QRNNLM:
    return QRNNLM(
        vocab_size=cfg.vocab_size,
        n_qubits=cfg.quantum.n_qubits,
        n_layers=cfg.quantum.n_circuit_layers,
        init_scale=cfg.quantum.init_scale,
        entangler="none" if cfg.quantum.ansatz == "ising" else "cnot_ring",
    )
